version: "3.2"
services:
  web_finder_mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d:ro
      - web_finder_mongo_volumes:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: webfinder
    ports:
      - 27018:27017
    networks:
      default:
      web_finder_internal:
        aliases:
          - web_finder_mongo

  web_finder:
    image: ecadagiani/webfinder:latest
    restart: always
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./config.json:/app/config.json
    environment:
      PORT: 3030
    networks:
      default:
      web_finder_internal:
        aliases:
          - web_finder

volumes:
  web_finder_mongo_volumes:

networks:
  default:
  web_finder_internal:
