version: "3.2"
services:
  web_finder_mongo:
    image: mongo:latest
    restart: always
    logging:
      driver: none
    volumes:
      - ./dev.mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro
      - web_finder_mongo_volumes:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: webfinder
    ports:
      - 27018:27017
    networks:
      default:
      web_finder_internal:
        aliases:
          - web_finder_mongo

  web_finder:
    build:
      context: .
      dockerfile: dev.dockerfile
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./src:/app/src
      - ./dev.config.json:/app/config.json
      - ./src/plugins/dev.PluginTest.js:/app/src/plugins/PluginTest.js
      - web_finder_node_volumes:/app/node_modules
    environment:
      PORT: 3030
    networks:
      default:
      web_finder_internal:
        aliases:
          - web_finder

volumes:
  web_finder_mongo_volumes:
  web_finder_node_volumes:

networks:
  default:
  web_finder_internal:
